In [62]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [63]:
import os
import numpy as np
from matplotlib import pyplot

from scipy import optimize

%matplotlib inline

In [64]:
data = np.loadtxt(os.path.join('/content/drive/MyDrive/colab/2doparcial/datasets/breast-cancer-wisconsin.txt'), delimiter=',')
data = data[:600]
data_trainer = data[600:]

X, y = data[:, :10], data[:, 10]
y[y == 2] = 0
y[y == 4] = 1
M, N = X.shape

In [66]:
def sigmoid(z):
    z = np.array(z)
    g = np.zeros(z.shape)
    g = 1 / (1 + np.exp(-z))
    return g

In [67]:
def costFunction(theta, X, y):
    m = y.size  # numero de ejemplos de entrenamiento

    J = 0
    grad = np.zeros(theta.shape)

    h = sigmoid(X.dot(theta.T))
    
    J = (1 / m) * np.sum(-y.dot(np.log(h)) - (1 - y).dot(np.log(1 - h)))
    grad = (1 / m) * (h - y).dot(X)
    
    return J, grad

In [68]:
m, n = X.shape
# Agraga el termino de intercepción a A

X = np.concatenate([np.ones((m, 1), dtype=int), X], axis=1)

array([[1.000000e+00, 1.000025e+06, 5.000000e+00, ..., 3.000000e+00,
        1.000000e+00, 1.000000e+00],
       [1.000000e+00, 1.002945e+06, 5.000000e+00, ..., 3.000000e+00,
        2.000000e+00, 1.000000e+00],
       [1.000000e+00, 1.015425e+06, 3.000000e+00, ..., 3.000000e+00,
        1.000000e+00, 1.000000e+00],
       ...,
       [1.000000e+00, 1.333063e+06, 5.000000e+00, ..., 3.000000e+00,
        1.000000e+00, 1.000000e+00],
       [1.000000e+00, 1.333495e+06, 3.000000e+00, ..., 2.000000e+00,
        1.000000e+00, 1.000000e+00],
       [1.000000e+00, 1.334659e+06, 5.000000e+00, ..., 1.000000e+00,
        1.000000e+00, 1.000000e+00]])

In [69]:
initial_theta = np.zeros(n+1)
cost, grad = costFunction(initial_theta, X, y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [79]:
options= {'maxiter': 100000}
res = optimize.minimize(costFunction,
                        initial_theta,
                        (X, y),
                        jac=True,
                        method='TNC',
                        options=options)
cost = res.fun

# Theta optimizada esta en la propiedad x
theta = res.x

# Imprimir theta en la pantalla
print('Costo con un valor de theta encontrado por optimize.minimize: {}'.format(cost))

print('theta:')
print('{}'.format(theta))

Costo con un valor de theta encontrado por optimize.minimize: 0.09722522186301973
theta:
[-9.39789186e+00  1.65317544e-07  5.26528048e-01 -4.44246108e-02
  3.72483002e-01  2.31821702e-01  9.23202127e-02  3.54673683e-01
  3.89219483e-01  1.09571953e-01  5.21141688e-01]


In [80]:
def predict(theta, X):
    m = X.shape[0] # Numero de ejemplo de entrenamiento
    p = np.zeros(m)

    p = np.round(sigmoid(X.dot(theta.T)))
    return p

In [82]:
prob = sigmoid(np.dot([1,1017122,8,10,10,8,7,10,9,7,1], theta))
print('{:.3f}'.format(prob))
# Compute accuracy on our training set
p = predict(theta, X)
print('Precisión de entrenamiento: {:.2f} %'.format(np.mean(p == y) * 100))
p

1.000


array([0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1.,
       1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0.,
       0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0.,
       0., 0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1.,
       0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1.,
       1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0.,
       0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0.,
       1., 0., 1., 1., 0.